package io.notable.ui_notelist.ui.test

const val TAG_NOTE_SEARCH_BAR = "TAG_NOTE_SEARCH_BAR"
const val TAG_NOTE_TITLE = "TAG_NOTE_TITLE"
const val TAG_NOTE_FILTER_BTN = "TAG_NOTE_FILTER_BTN"
const val TAG_NOTE_FILTER_DIALOG = "TAG_NOTE_FILTER_DIALOG"
const val TAG_NOTE_FILTER_DIALOG_DONE = "TAG_NOTE_FILTER_DIALOG_DONE"
const val TAG_NOTE_FILTER_NOTE_CHECKBOX = "TAG_NOTE_FILTER_NOTE_CHECKBOX"
const val TAG_NOTE_FILTER_DESC = "TAG_NOTE_FILTER_DESC"
const val TAG_NOTE_FILTER_ASC = "TAG_NOTE_FILTER_ASC"
const val TAG_NOTE_FILTER_LAST_UPDATE = "TAG_NOTE_FILTER_LAST_UPDATE"
const val TAG_NOTE_DATE = "TAG_NOTE_DATE"