name: Run unit tests & lint

defaults:
  run:
    working-directory: ./server

on:
  push:
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "microsoft"
          cache: gradle
      - name: Grant Permission to Execute
        run: chmod +x gradlew
      - name: Run Kotlin Linter
        run: ./gradlew detekt --no-daemon

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: notable_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "microsoft"
          cache: gradle
      - name: Grant Permission to Execute
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test --no-daemon